name: build

on: [push]

env:
  REGISTRY: cr.yandex
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-push-image:
    if: github.event_name == 'push'
    runs-on: yandex-runner-org
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: json_key
          password: ${{ secrets.YANDEX_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.YANDEX_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value={{sha}},event=branch
            type=ref,event=tag
            type=raw,value=latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./rails_app
          file: ./rails_app/Dockerfile
          provenance: false
          push: false
          pull: true
          load: true
          builder: ${{ steps.buildx.outputs.name }}
          # Cache to yandex container registry
          cache-from: type=registry,ref=${{ secrets.YANDEX_REGISTRY }}/${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,mode=max,ref=${{ secrets.YANDEX_REGISTRY }}/${{ env.IMAGE_NAME }}:cache,oci-mediatypes=true,image-manifest=true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}